---
- hosts: webserver
  become: yes   
  tasks:  
    - name: install jdk on ubuntu
      apt: 
        name: "{{javaonubuntu}}"
        state: present
      when: ansible_os_family == "Debian"

    - name: install jdk on amazon
      apt: 
        name: "{{javaonamazon}}"
        state: present
      when: ansible_os_family == "RedHat"
