---
- hosts: all
  become: yes
  tasks:
    - name: install jdk on ubuntu
      apt: 
        name: openjdk-8-jre-headless
        state: present
      when: ansible_os_family == "Debian"

    - name: install jdk on amazon linux
      yum:
        name: java-1.8.0-openjdk
        state: started
      when: ansible_os_family == "RedHat"