---
- hosts: all
  become: yes
  tasks: 
    - name: install webserver
      apt: 
        name: apache2
        state: present
    
    - name: start web server
      service:
        name: apache2
        state: started

    - name: copy index file to nodes web page
      template:
        src: index.j2
        dest: /var/www/html/index.html

    - name: restart web server
      service: 
        name: apache2
        state: restarted
